export { default as Nav } from "./Nav"
export { default as Header } from "./Header"
export { default as Work } from "./Work"
export { default as Contact } from "./Contact"
export { default as Footer} from "./Footer"
export { default as About } from "./About"